# Generated by Django 5.0.2 on 2024-03-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('pages', models.IntegerField()),
                ('author', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
